services:
  rabbit:
    container_name: email_sender
    image: rabbitmq:4.2.4-management-alpine

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
